# To use this, download VSCode extension:
# https://github.com/Huachao/vscode-restclient

@API=http://localhost:5182/api
@GUID={{create.response.body.$}}
@TOKEN={{login.response.body.token}}

### Login as Bob
# @name login

POST {{API}}/account/login
content-type: application/json

{
    "email": "bob@test.com",
    "password": "Passw0rd"
}

### Login as Paul
# @name login

POST {{API}}/account/login
content-type: application/json

{
    "email": "paul@test.com",
    "password": "PaulR0cks"
}

### Login - failure

POST {{API}}/account/login
content-type: application/json

{
    "email": "bob@test.com",
    "password": "Bad password"
}

### Register Bob

POST {{API}}/account/register
Content-Type: application/json

{
    "email": "bob@test.com",
    "username": "bob",
    "displayName": "bob",
    "password": "Passw0rd"
}

### Register Paul

POST {{API}}/account/register
Content-Type: application/json

{
    "email": "paul@test.com",
    "username": "paul",
    "displayName": "pauly",
    "password": "PaulR0cks"
}

### Register - failure

POST {{API}}/account/register
Content-Type: application/json

{
    "email": "",
    "username": "",
    "displayName": "",
    "password": ""
}

### User

GET {{API}}/account
Authorization: Bearer {{TOKEN}}

### List

GET {{API}}/activities
Authorization: Bearer {{TOKEN}}

### Create 
# @name create

POST {{API}}/activities HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
    "title": "Title from HTTP client",
    "description": "Such HTTP",
    "category": "Post",
    "date": "{{$datetime iso8601}}",
    "city": "Tromsø",
    "venue": "Ishavskatedralen"
}

### Create - failure

POST {{API}}/activities HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}

{ }

### Details

GET {{API}}/activities/{{GUID}}
Authorization: Bearer {{TOKEN}}

### Update

PUT {{API}}/activities/{{GUID}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "title": "Title from HTTP client",
    "description": "Some",
    "category": "Post",
    "date": "{{$datetime iso8601}}",
    "city": "Tromsø",
    "venue": "changes"
}

### Delete

DELETE {{API}}/activities/{{GUID}}
Authorization: Bearer {{TOKEN}}

### Attend

POST {{API}}/activities/{{GUID}}/attend
Authorization: Bearer {{TOKEN}}
