# To use this, download VSCode extension:
# https://github.com/Huachao/vscode-restclient

@API=http://localhost:5182/api
@GUID={{create.response.body.$}}
@TOKEN={{login.response.body.token}}
@PHOTO_ID={{photo.response.body.id}}
@PHOTO_URL={{photo.response.body.url}}
@USERNAME={{login.response.body.username}}

### Login as Bob
# @name login

POST {{API}}/account/login
content-type: application/json

{
    "email": "bob@test.com",
    "password": "Passw0rd"
}

### Login as Paul
# @name login

POST {{API}}/account/login
content-type: application/json

{
    "email": "paul@test.com",
    "password": "PaulR0cks"
}

### Login - failure

POST {{API}}/account/login
content-type: application/json

{
    "email": "bob@test.com",
    "password": "Bad password"
}

### Register Bob

POST {{API}}/account/register
Content-Type: application/json

{
    "email": "bob@test.com",
    "username": "bob",
    "displayName": "bob",
    "password": "Passw0rd"
}

### Register Paul

POST {{API}}/account/register
Content-Type: application/json

{
    "email": "paul@test.com",
    "username": "paul",
    "displayName": "pauly",
    "password": "PaulR0cks"
}

### Register - failure

POST {{API}}/account/register
Content-Type: application/json

{
    "email": "",
    "username": "",
    "displayName": "",
    "password": ""
}

### User

GET {{API}}/account
Authorization: Bearer {{TOKEN}}

### List Activities

GET {{API}}/activities
Authorization: Bearer {{TOKEN}}

### Create Activity
# @name create

POST {{API}}/activities HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
    "title": "Title from HTTP client",
    "description": "Such HTTP",
    "category": "Post",
    "date": "{{$datetime iso8601}}",
    "city": "Tromsø",
    "venue": "Ishavskatedralen"
}

### Create - failure

POST {{API}}/activities HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}

{ }

### Activity Details

GET {{API}}/activities/{{GUID}}
Authorization: Bearer {{TOKEN}}

### Update Activity

PUT {{API}}/activities/{{GUID}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "title": "Title from HTTP client",
    "description": "Some",
    "category": "Post",
    "date": "{{$datetime iso8601}}",
    "city": "Tromsø",
    "venue": "changes"
}

### Delete Activity

DELETE {{API}}/activities/{{GUID}}
Authorization: Bearer {{TOKEN}}

### Activity - Toggle attendance

POST {{API}}/activities/{{GUID}}/attend
Authorization: Bearer {{TOKEN}}

### Upload Photo
# @name photo

POST {{API}}/photos
Authorization: Bearer {{TOKEN}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="File"; filename="author.png"

< ./author.png
--WebAppBoundary--

### Delete Photo

DELETE {{API}}/photos/{{PHOTO_ID}}
Authorization: Bearer {{TOKEN}}

### Download Photo

GET {{PHOTO_URL}}

### Set Main

POST {{API}}/photos/{{PHOTO_ID}}/setMain
Authorization: Bearer {{TOKEN}}

### Profile

GET {{API}}/profiles/{{USERNAME}}
Authorization: Bearer {{TOKEN}}
